apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  - name: selenium-node-chrome-1
    image: selenium/node-chrome:3.141.59-20210607
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/ctr/
    ports:
     - containerPort: 5900
    env:
     - name: HUB_HOST
       value: "selenium-srv"
     - name: HUB_PORT
       value: "4444"

  - name: selenium-node-chrome
    image: selenium/node-chrome:3.141.59-20210607
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/ctr/
    ports:
     - containerPort: 5900
    env:
     - name: HUB_HOST
       value: "selenium-srv"
     - name: HUB_PORT
       value: "4444"
