apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 4
  selector:
    matchLabels:
      app: selenium-node-chrome
  strategy: {}
  template:
    metadata:
      name: selenium-node-chrome
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:3.141.59-20210607
          ports:
            - containerPort: 5900
          env:
            - name: HUB_HOST
              value: "selenium-srv"
            - name: HUB_PORT
              value: "4444"
          resources: {}
      restartPolicy: Always
status: {}
